# Generated by Django 3.2.5 on 2021-07-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
