# Generated by Django 3.2.5 on 2021-07-19 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_salary_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jobs', to='calculator.job'),
        ),
    ]
